Repository HashnodeWithAngular/angular-primeng, pull requests merged in 2024-05, with the labels that each got.

#70 feature(settings-dialog): input validations and error handling
  angular-primeng-app/src/app/components/posts/posts.component.scss
  angular-primeng-app/src/app/components/series/series.component.scss
  angular-primeng-app/src/app/partials/settings-dialog/settings-dialog.component.html
  angular-primeng-app/src/app/partials/settings-dialog/settings-dialog.component.scss
  angular-primeng-app/src/app/partials/settings-dialog/settings-dialog.component.ts
  angular-primeng-app/src/styles.scss
Labels: 🌟feature, 🔒 security, core team work

#73 feat(core team work): updating angular and dependencies
  angular-primeng-app/package-lock.json
  angular-primeng-app/package.json
Labels: core team work

#75 fix(post-details) : Inconsistency in GraphQL Query for Author Data
  angular-primeng-app/src/app/components/post-details/post-details.component.html
  angular-primeng-app/src/app/graphql.operations.ts
  angular-primeng-app/src/app/models/post.ts
Labels: 🐛 bug, GraphGL
