Repository HashnodeWithAngular/angular-primeng, pull requests merged in 2024-04, with the labels that each got.

#60 feat(component): add new feature If it is a team blog,then display group of author profile images.
  angular-primeng-app/src/app/components/post-details/post-details.component.html
  angular-primeng-app/src/app/components/post-details/post-details.component.ts
  angular-primeng-app/src/app/graphql.operations.ts
  angular-primeng-app/src/app/models/post.ts
Labels: 🌟feature, 🛰️ apollo angular, GraphGL, 🖼️ images & icons, 🎨 styling

#63 docs(contributing.md): more updates
  CONTRIBUTING.md
Labels: 📄 documentation, core team work

#64 feat(post-details): file structure
  angular-primeng-app/src/app/components/post-details/post-details.component.ts
Labels: 📁 file structure, core team work

#65 docs(contributing.md): update and issue tracker links
  CONTRIBUTING.md
Labels: 📄 documentation, core team work
