Repository HashnodeWithAngular/angular-primeng, pull requests merged in 2024-03, with the labels that each got.

#12 latest updates name
  CONTRIBUTING.md
  LICENSE
  README.md
  angular-primeng-app/README.md
  angular-primeng-app/dist/browser/index.html
  angular-primeng-app/dist/server/index.server.html
  angular-primeng-app/src/app/components/footer/footer.component.html
  angular-primeng-app/src/app/components/header/header.component.html
  angular-primeng-app/src/app/graphql.operations.ts
  angular-primeng-app/src/assets/images/anguhashblog-logo.jpg
  angular-primeng-app/src/index.html
Labels: 📄 documentation, 📁 file structure

#15 Feat(meta tags): og image title description
  angular-primeng-app/dist/3rdpartylicenses.txt
  angular-primeng-app/dist/browser/assets/images/anguhashblog-logo.jpg
  angular-primeng-app/dist/browser/assets/images/angular-primeng-dark-anguhashblog.jpg
  angular-primeng-app/dist/browser/assets/images/angular-primeng-light-anguhashblog.jpg
  angular-primeng-app/dist/browser/assets/images/hashnode-logo-white.png
  angular-primeng-app/dist/browser/assets/themes/dark.scss
  angular-primeng-app/dist/browser/assets/themes/light.scss
  angular-primeng-app/dist/browser/chunk-4KWLFWZZ.js
  angular-primeng-app/dist/browser/chunk-5IYU7X6J.js
  angular-primeng-app/dist/browser/chunk-5W73IEJQ.js
  angular-primeng-app/dist/browser/chunk-BSR3TW2G.js
  angular-primeng-app/dist/browser/chunk-M2IUTPRF.js
  angular-primeng-app/dist/browser/chunk-PTRLSXG5.js
  angular-primeng-app/dist/browser/chunk-RV6LF5VC.js
  angular-primeng-app/dist/browser/dark.css
  angular-primeng-app/dist/browser/favicon.ico
  angular-primeng-app/dist/browser/index.html
  angular-primeng-app/dist/browser/light.css
  angular-primeng-app/dist/browser/main-NHZ4RMZ7.js
  angular-primeng-app/dist/browser/main-OUFQJIGP.js
  angular-primeng-app/dist/browser/styles-IYO4AA6T.css
  angular-primeng-app/dist/browser/styles-KR6GWFYW.css
  angular-primeng-app/dist/server/chunk-7HIX4W35.mjs
  angular-primeng-app/dist/server/chunk-AB6R3DKH.mjs
  angular-primeng-app/dist/server/chunk-AXW2RRA2.mjs
  angular-primeng-app/dist/server/chunk-DOEG56EA.mjs
  angular-primeng-app/dist/server/chunk-ETOGTFRM.mjs
  angular-primeng-app/dist/server/chunk-J65WZKML.mjs
  angular-primeng-app/dist/server/chunk-KLEAS67C.mjs
  angular-primeng-app/dist/server/chunk-ODEAQAGT.mjs
  angular-primeng-app/dist/server/chunk-PUQEUYKV.mjs
  angular-primeng-app/dist/server/chunk-PUYSBYUS.mjs
  angular-primeng-app/dist/server/chunk-REPUMSU6.mjs
  angular-primeng-app/dist/server/chunk-X2NXM42Z.mjs
  angular-primeng-app/dist/server/index.server.html
  angular-primeng-app/dist/server/main.server.mjs
  angular-primeng-app/dist/server/render-utils.server.mjs
  angular-primeng-app/dist/server/server.mjs
  angular-primeng-app/src/assets/images/angular-primeng-dark-anguhashblog.jpg
  angular-primeng-app/src/assets/images/angular-primeng-dark.jpg
  angular-primeng-app/src/assets/images/angular-primeng-light-anguhashblog.jpg
  angular-primeng-app/src/assets/images/angular-primeng-light.jpg
  angular-primeng-app/src/index.html
Labels: 🌟feature, 🖼️ images & icons

#23 readme update
  README.md
  anguhashblog.png
Labels: 📄 documentation, 🖼️ images & icons

#29 Update styles.scss
  angular-primeng-app/src/styles.scss
Labels: 🐛 bug, 🖼️ images & icons, 🎨 styling

#35 fix(pipe): the native DomSanitizer pipe was meant to be used
  angular-primeng-app/src/app/components/post-details/post-details.component.html
  angular-primeng-app/src/app/components/post-details/post-details.component.ts
  angular-primeng-app/src/app/pipes/sanitizer-html.pipe.spec.ts
  angular-primeng-app/src/app/pipes/sanitizer-html.pipe.ts
Labels: 🐛 bug, 🔒 security

#38 Multiple Issues - features and fixes
  angular-primeng-app/src/app/components/footer/footer.component.ts
  angular-primeng-app/src/app/components/header/header.component.html
  angular-primeng-app/src/app/components/header/header.component.scss
  angular-primeng-app/src/app/components/header/header.component.ts
  angular-primeng-app/src/app/components/post-details/post-details.component.html
  angular-primeng-app/src/app/components/post-details/post-details.component.scss
  angular-primeng-app/src/app/components/post-details/post-details.component.ts
  angular-primeng-app/src/app/components/posts/posts.component.html
  angular-primeng-app/src/app/components/posts/posts.component.scss
  angular-primeng-app/src/app/components/posts/posts.component.ts
  angular-primeng-app/src/app/components/series/series.component.html
  angular-primeng-app/src/app/components/series/series.component.scss
  angular-primeng-app/src/app/components/series/series.component.ts
  angular-primeng-app/src/app/components/sidenav/sidenav.component.ts
  angular-primeng-app/src/app/directives/youtube-video-embed.directive.spec.ts
  angular-primeng-app/src/app/directives/youtube-video-embed.directive.ts
  angular-primeng-app/src/app/graphql.operations.ts
  angular-primeng-app/src/app/partials/follow-dialog/follow-dialog.component.html
  angular-primeng-app/src/app/partials/follow-dialog/follow-dialog.component.scss
  angular-primeng-app/src/app/partials/follow-dialog/follow-dialog.component.spec.ts
  angular-primeng-app/src/app/partials/follow-dialog/follow-dialog.component.ts
  angular-primeng-app/src/app/partials/search-dialog/search-dialog.component.html
  angular-primeng-app/src/app/partials/search-dialog/search-dialog.component.ts
  angular-primeng-app/src/app/partials/settings-dialog/settings-dialog.component.html
  angular-primeng-app/src/app/partials/settings-dialog/settings-dialog.component.scss
  angular-primeng-app/src/app/partials/settings-dialog/settings-dialog.component.spec.ts
  angular-primeng-app/src/app/partials/settings-dialog/settings-dialog.component.ts
  angular-primeng-app/src/app/pipes/sanitizer-html.pipe.spec.ts
  angular-primeng-app/src/app/pipes/sanitizer-html.pipe.ts
  angular-primeng-app/src/app/services/blog.service.ts
  angular-primeng-app/src/styles.scss
Labels: 🐛 bug, 🌟feature, 🔀 routing, 📁 file structure, GraphGL, 🖼️ images & icons, RxJS, 🎨 styling, custom directive

#42 feat(docs): issue templates yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: 📄 documentation

#45 feat(header, layout): layout component removed, routing is normal, header with conditional elements
  angular-primeng-app/src/app/app.component.html
  angular-primeng-app/src/app/app.component.scss
  angular-primeng-app/src/app/app.component.ts
  angular-primeng-app/src/app/app.routes.ts
  angular-primeng-app/src/app/components/header/header.component.html
  angular-primeng-app/src/app/components/header/header.component.scss
  angular-primeng-app/src/app/components/header/header.component.ts
  angular-primeng-app/src/app/components/layout/layout.component.html
  angular-primeng-app/src/app/components/layout/layout.component.scss
  angular-primeng-app/src/app/components/layout/layout.component.spec.ts
  angular-primeng-app/src/app/components/layout/layout.component.ts
  angular-primeng-app/src/app/components/post-details/post-details.component.html
  angular-primeng-app/src/app/components/post-details/post-details.component.scss
  angular-primeng-app/src/app/components/post-details/post-details.component.ts
Labels: 🌟feature, 🔀 routing, 📁 file structure, 🎨 styling

#46 basic workflows
  .github/workflows/issue.yml
  .github/workflows/triage.yml
Labels: core team work

#48 docs(changelog): changelog generated
  angular-primeng-app/CHANGELOG.md
Labels: 📄 documentation

#47 feat(posts, series): load more posts on scroll
  angular-primeng-app/src/app/components/posts/posts.component.html
  angular-primeng-app/src/app/components/posts/posts.component.scss
  angular-primeng-app/src/app/components/posts/posts.component.ts
  angular-primeng-app/src/app/components/series/series.component.html
  angular-primeng-app/src/app/components/series/series.component.scss
  angular-primeng-app/src/app/components/series/series.component.ts
  angular-primeng-app/src/app/directives/infinite-scroll.directive.spec.ts
  angular-primeng-app/src/app/directives/infinite-scroll.directive.ts
  angular-primeng-app/src/app/graphql.operations.ts
  angular-primeng-app/src/app/models/post.ts
  angular-primeng-app/src/app/services/blog.service.ts
Labels: 🌟feature, 🎨 styling, custom directive

#50 docs(templates): issue templates
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
  angular-primeng-app/src/app/components/posts/posts.component.ts
Labels: 📄 documentation

#55 feat(sitewide): initial responsivness mobile media query
  angular-primeng-app/angular.json
  angular-primeng-app/src/app/components/header/header.component.html
  angular-primeng-app/src/app/components/header/header.component.scss
  angular-primeng-app/src/app/components/post-details/post-details.component.scss
  angular-primeng-app/src/app/components/posts/posts.component.scss
  angular-primeng-app/src/app/components/series/series.component.scss
  angular-primeng-app/src/app/components/sidenav/sidenav.component.scss
  angular-primeng-app/src/app/partials/search-dialog/search-dialog.component.scss
  angular-primeng-app/src/styles.scss
Labels: 🌟feature, 📱responsiveness, 🎨 styling

#57 feat(sitewide): add scroll to top button to conditionally appear in longer pages
  angular-primeng-app/src/app/app.component.html
  angular-primeng-app/src/app/app.component.scss
  angular-primeng-app/src/app/app.component.ts
Labels: 🌟feature, 🖼️ images & icons, 🎨 styling

#58 minor adjustments
  angular-primeng-app/src/app/app.component.html
  angular-primeng-app/src/app/app.component.scss
  angular-primeng-app/src/app/app.component.ts
Labels: core team work

#59 changing something marked as deprecated
  angular-primeng-app/src/app/app.component.ts
Labels: core team work
